### ISSUE TITLE
about the wave equation case

### ISSUE THREAD

**Issue by norery** [cselab/odil#2]
Thank you for your wonderful code. I am very interested in this method. 

Is it possible to upload the relevant code about the case of solving the wave equation in the article? This will serve as an example to learn this method better.

**Comment by pkarnakov** [comment]
Thanks for your interest. I'll try to release the code for the wave equation in a couple of days, meanwhile I think some [examples](https://github.com/cselab/odil/tree/main/examples), in particular `heat` or `poisson`, demonstrate the relevant features.

**Comment by norery** [comment]
Thank you so much, looking forward to it.

**Comment by Lucky-Lee-codemaker** [comment]
Thank you for sharing the code of your wonderful article. I also look forward to your release of the code related to the wave equation

**Comment by Lucky-Lee-codemaker** [comment]
Hello, I have some doubts about the content of the paper. What is the shape of C here? Is it a one-dimensional vector? Or is it a matrix similar to one hot encoding? Why is its length equal to the number of grids? Another question is the formula in the picture on the right, I didn't understand its meaning. I hope you can answer it. Thank you very much!
![1731376943991](https://github.com/user-attachments/assets/976c834e-aa56-49bf-b1e5-5e3449c30f6c)
![1731376922114](https://github.com/user-attachments/assets/bb7c1d34-809c-4a98-b1e9-1d90285e9045)

**Comment by Lucky-Lee-codemaker** [comment]
Thank you very much for your answer. I would like to confirm again, If in a 3-dimensional space, does C represent a 3-dimensional tensor? Can the elements in C be seen as continuous integers starting from 0? Does the discrete field represent physical fields such as velocity fields? "R^C denotes the set of all discrete fields on C", should R^C be replaced with (R^C)^Nu here?

**Comment by Lucky-Lee-codemaker** [comment]
Thank you very much for your answer. I would like to confirm again, If in a 3-dimensional space, does C represent a 3-dimensional tensor? Can the elements in C be seen as continuous integers starting from 0? Does the discrete field represent physical fields such as velocity fields? "R^C denotes the set of all discrete fields on C", should R^C be replaced with (R^C)^Nu here? Is the first gradient based method still relying on neural networks? We look forward to your reply！

**Comment by pkarnakov** [comment]
Yes, `C` can be seen as integers enumerating all cells. Yes, the discrete field represents physical quantities. `R^C` denotes the set of all scalar discrete fields, `(R^C)^Nu` is then a tuple of `Nu` fields. The gradient-based method does not rely on neural networks (unless they are used to represent unknown functions), all quantities are on the grid.

**Comment by Lucky-Lee-codemaker** [comment]
Thank you very much for your reply! This is very helpful for me to understand this article.
