### ISSUE TITLE
About the Poisson example

### ISSUE THREAD

**Issue by eqfwrg424535** [cselab/odil#4]
Hello,

    I am a Postdoc working in China University of Geoscience. I am interested in your work on the new algorithm for forward and inverse PDEs. And when I was testing the Poisson example, the following errors turned up. I have no idea how to fix them, could you please help me with that? Appreciate a lot.

ModuleNotFoundError                       Traceback (most recent call last)
D:\Anaconda3\lib\site-packages\odil\runtime.py in <module>()
     36     try:
---> 37         import jax
     38         backend_name = 'jax'

ModuleNotFoundError: No module named 'jax'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-3-ee48eae909f1> in <module>()
    322 
    323 if __name__ == "__main__":
--> 324     main()

<ipython-input-3-ee48eae909f1> in main()
    310 def main():
    311     args = parse_args()
--> 312     odil.setup_outdir(args)
    313     problem, state = make_problem(args)
    314     callback = odil.make_callback(problem,

D:\Anaconda3\lib\site-packages\odil\util.py in setup_outdir(args, relpath_args)
    347     '''
    348     from . import runtime
--> 349     mod = runtime.mod
    350     outdir = args.outdir
    351     os.makedirs(outdir, exist_ok=True)

D:\Anaconda3\lib\importlib\util.py in __getattribute__(self, attr)
    243             elif id(attrs_now[key]) != id(attrs_then[key]):
    244                 attrs_updated[key] = value
--> 245         self.__spec__.loader.exec_module(self)
    246         # If exec_module() was used directly there is no guarantee the module
    247         # object was put into sys.modules.

D:\Anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

D:\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

D:\Anaconda3\lib\site-packages\odil\runtime.py in <module>()
     40         sys.stderr.write(
     41             f"Cannot select a default backend. Tried: tensorflow, jax\n")
---> 42         exit(1)
     43 
     44 if backend_name == 'tf':

NameError: name 'exit' is not defined

**Comment by pkarnakov** [comment]
You need to install `jax` or `tensorflow`. Do you have any of those?

**Comment by eqfwrg424535** [comment]
It has been solved, thanks!











在 2024-11-03 16:46:14，"Petr Karnakov" ***@***.***> 写道：

You need to install jax or tensorflow. Do you have any of those?

**Comment by Lucky-Lee-codemaker** [comment]
Hello, I noticed that you have a line of code called 'from odil import printlog' in the possion.by file, but I did not see a script named printlog in the odil directory.
