### ISSUE TITLE
About the wave case

### ISSUE THREAD

**Issue by Jane-JWang** [cselab/odil#9]
Thanks for sharing the code!
I've run into some problems when replicating the wave case:
1. The image of the solution at `[-1,1] x [0,1]`
<img width="503" alt="image" src="https://github.com/user-attachments/assets/d2ecdf36-628f-447a-aa4d-6911a5ff1f55">

but what i've got looks like:
<img width="425" alt="image" src="https://github.com/user-attachments/assets/dd46c227-0afa-4fde-8a67-d398fca493ac">

where y-axis represents the "t" and x-axis represents the "x". It seems that the image of the solution provided in the article is not within the given range `[-1,1]x[0,1]`, so what's the actual range?

2. About cell centers
<img width="488" alt="image" src="https://github.com/user-attachments/assets/013128a7-cff0-46cf-9353-5ff92f600e6f">

It seems that when `i = Nx`, the cell center is located at `1 + 0.5 dx` outside the domain, which is pretty weird(is there some unmentioned math techniques?). I think `-1+(i-0.5)dx` is more reasonable where every cell is located inside the domain.

I'm now stuck with this case and I would appreciate it very much if you could upload the example for wave equation. Thanks!

**Comment by pkarnakov** [comment]
I've added an example in https://github.com/cselab/odil/tree/main/examples/wave

1. The definition of the reference solution in the example matches the one in the paper (unless I'm missing something). In particular, this should be an even function along X (which is not the case in your image).

2. Yes, this is a typo in the paper, thanks for noticing it. The correct definition is `x_i = -1+(i-0.5)*dx` for `i=1..Nx`.

**Comment by Jane-JWang** [comment]
Thanks for your reply!
<img width="402" alt="image" src="https://github.com/user-attachments/assets/228f8dd2-996a-4991-a38b-651ffec0c7ef">

<img width="194" alt="image" src="https://github.com/user-attachments/assets/a0bf616e-9b82-4dbe-8295-57c27f027e81">

It seems that there's a typo in the second cos part where `x+t+0.5` should be `x+t-0.5` as implemented in the code. 
Again thanks for your patience and your code!

**Comment by Jhon1h** [comment]
对于wave的例子，我得到的训练结果与您的不一致，请问这个是需要调整哪些参数呢？

**Comment by Jane-JWang** [comment]
> 对于wave的例子，我得到的训练结果与您的不一致，请问这个是需要调整哪些参数呢？

我这里能够训练出正确的解，可以尝试调整一下kimp，对训练结果提升比较大

**Comment by Jhon1h** [comment]
我是一名初学者，我可以想你您请教一下这个kimp是什么意思嘛

**Comment by Jhon1h** [comment]
> > 对于wave的例子，我得到的训练结果与您的不一致，请问这个需要调整哪些参数呢？
> 
> 我能够在这里训练出正确的解，可以尝试训练调整一下kimp，对结果提升比较大

我是一名初学者，我可以向您请教一下这个kimp是什么含义吗

**Comment by Jhon1h** [comment]
> > > > 对于wave的例子，我得到的训练结果与您的不一致，请问这个需要调整哪些参数呢？
> > > 
> > > 
> > > 我能够在这里训练出正确的解，可以尝试训练调整一下kimp，对结果提升比较大
> > 
> > 
> > 我是一名初学者，我可以向您请教一下这个金条的意义是什么？
> 
> kimp:=k-impose，指在残差中以多大权重增加终极条件和边界条件

好的，非常感谢您的指导，谢谢您！我再仔细研究一下
